version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:261766457957:task-definition/aws-currency-exchange-service-h2-task:4"
        LoadBalancerInfo:
          ContainerName: "aws-currency-exchange-service-h2"
          ContainerPort: "80"
        PlatformVersion: "LATEST"